apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k3s
  template:
    metadata:
      name: hello-pod
      labels:
        app: hello-k3s
    spec:
      containers:
      - name: hello-container
        image: ghcr.io/adrianstudio/hello-app:v1
        ports:
        - containerPort: 8080
