apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: apps
  labels:
     app: hello-k3s
spec:
  type: NodePort
  ports:
    - port:  8080
      targetPort: 8080
      nodePort: 30082
  selector:
    app: hello-k3s
