apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    type: front-end
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
        type: front-end
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
  selector:
    matchLabels:
      app: grafana
